version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    environment:
      - PORT
    env_file:
      - .env
    init: true
    ports:
      - "${PORT}:${PORT}"
    tty: true
